version = 0.1

[default.deploy.parameters]
stack_name = "quadtree-api"
resolve_s3 = true
s3_prefix = "quadtree-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BackendUrl=\"http://44.206.225.167:8080\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
